### PR TITLE
Fixed CLI

### PR DESCRIPTION
**Pull request by Gretel5X**
Added wheel to pip and installing the necessary environments to platformio

### CODE REVIEW

**Comment by Gretel5X** [comment]
the last statement `pio update` might be unnecessary but does not hurt

**Comment by martinjaeger** [comment]
What does wheel do?

**Comment by martinjaeger** [comment]
And what's the difference between `checkout@v1` and `checkout@v2`?

**Comment by Gretel5X** [comment]
> What does wheel do?

wheel is a pip tool to package dependencies: https://pip.pypa.io/en/stable/reference/pip_wheel/
It said `using legacy install 'setup.py' because wheel not installed` before, so I added it

**Comment by Gretel5X** [comment]
https://github.com/LibreSolar/esp32-edge-firmware/pull/19#issuecomment-802805622

mainly improved performance :https://github.com/actions/checkout

**Review by martinjaeger — APPROVED** [review]

**Comment by martinjaeger** [comment]
Great, thanks for fixing the issue. Feel free to merge.

**Pull request merged**
